_BASE_: base-image_retri.yml

INPUT:
  SIZE_TRAIN: [0,]
  SIZE_TEST: [0,]

SOLVER:
  MAX_EPOCH: 100

  BASE_LR: 0.003
  ETA_MIN_LR: 0.00003

  MOMENTUM: 0.99
  NESTEROV: True

TEST:
  RECALLS: [ 1, 10, 20, 30, 40, 50 ]

DATASETS:
  NAMES: ("InShop",)
  TESTS: ("InShop",)

OUTPUT_DIR: projects/FastRetri/logs/r50-base_inshop