class VersionSchemaField:
    """String constants used as column names across snapshot table schemas."""

    SCHEMA_VERSION = "schema_version"
    TABLES = "tables"
    NAME = "name"
    PATH = "path"
    ROW_COUNT = "row_count"
    SRC_DATASET_ID = "src_dataset_id"
    PARENT_SRC_DATASET_ID = "parent_src_dataset_id"
    FULL_PATH = "full_path"
    DESCRIPTION = "description"
    SRC_VIDEO_ID = "src_video_id"
    SRC_VOLUME_ID = "src_volume_id"
    HASH = "hash"
    LINK = "link"
    FRAMES_COUNT = "frames_count"
    FRAME_WIDTH = "frame_width"
    FRAME_HEIGHT = "frame_height"
    FRAMES_TO_TIMECODES = "frames_to_timecodes"
    META = "meta"
    CUSTOM_DATA = "custom_data"
    CREATED_AT = "created_at"
    UPDATED_AT = "updated_at"
    ANN_JSON = "ann_json"
    JSON = "json"
    ANNOTATION = "annotation"
    SRC_OBJECT_ID = "src_object_id"
    CLASS_NAME = "class_name"
    KEY = "key"
    TAGS_JSON = "tags_json"
    SRC_FIGURE_ID = "src_figure_id"
    FRAME_INDEX = "frame_index"
    GEOMETRY_TYPE = "geometry_type"
    GEOMETRY_JSON = "geometry_json"

    # Image snapshot tables (v2.0.0).
    SRC_IMAGE_ID = "src_image_id"
    PARENT_SRC_IMAGE_ID = "parent_src_image_id"
    MIME = "mime"
    EXT = "ext"
    SIZE = "size"
    WIDTH = "width"
    HEIGHT = "height"
    CREATED_BY_ID = "created_by_id"
    CLASS_ID = "class_id"
    GEOMETRY_META_JSON = "geometry_meta_json"
    PRIORITY = "priority"
    RELATED_DATA_ID = "related_data_id"
    DOWNLOAD_ID = "download_id"
    OFFSET_START = "offset_start"
    OFFSET_END = "offset_end"

    # Video figure fields that only ann_json used to carry (schema v2.1.0).
    TRACK_ID = "track_id"
    SMART_TOOL_INPUT = "smart_tool_input"
    NN_CREATED = "nn_created"
    NN_UPDATED = "nn_updated"

    # The tags table: one row per tag assignment, whatever it hangs on.
    TAG_ASSIGNMENT_ID = "tag_assignment_id"
    OWNER_TYPE = "owner_type"
    OWNER_ID = "owner_id"
    SRC_ITEM_ID = "src_item_id"
    TAG_ID = "tag_id"
    VALUE_JSON = "value_json"
    FRAME_FROM = "frame_from"
    FRAME_TO = "frame_to"
    IS_FINISHED = "is_finished"
    NON_FINAL_VALUE = "non_final_value"
    LABELER_LOGIN = "labeler_login"
