_BASE_: Base-kd.yml

MODEL:
  BACKBONE:
    DEPTH: 34x
    FEAT_DIM: 512
    WITH_IBN: False

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: projects/FastDistill/logs/dukemtmc/r34