ARG SSH_PASSWORD
ARG DOCKER_IMAGE
FROM ${DOCKER_IMAGE}
#FROM docker.deepsystems.io/supervisely/five/import-video-sly:master

RUN echo 'root:${SSH_PASSWORD}'

##############################################################################
# Additional project libraries
##############################################################################

#RUN apt-get update && apt-get install -y openssh-server
#RUN mkdir /var/run/sshd
#RUN echo 'root:${SSH_PASSWORD}' | chpasswd
#RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
#RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
#ENV NOTVISIBLE "in users profile"
#RUN echo "export VISIBLE=now" >> /etc/profile