_BASE_: base-image_retri.yml

SOLVER:
  MAX_EPOCH: 100

  BASE_LR: 0.003
  ETA_MIN_LR: 0.00003

  MOMENTUM: 0.99
  NESTEROV: True

TEST:
  RECALLS: [1, 10, 100, 1000]

DATASETS:
  NAMES: ("SOP",)
  TESTS: ("SOP",)

OUTPUT_DIR: projects/FastRetri/logs/r50-base_sop