_BASE_: face_base.yml

MODEL:

  BACKBONE:
    NAME: build_resnetIR_backbone
    DEPTH: 100x
    FEAT_DIM: 25088 # 512x7x7
    WITH_SE: True

  HEADS:
    PFC:
      ENABLED: True

OUTPUT_DIR: projects/FastFace/logs/ir_se101-ms1mv2-circle
