from supervisely.solution.components.automation_widget.automation_widget import AutomationWidget, Automation
from supervisely.solution.components.tasks_history.tasks_history import TasksHistoryWidget
