# Dockerfile for base-py-sdk with Ubuntu 24.04 + Python 3.12
# https://hub.docker.com/r/supervisely/base-py-sdk

# Using new base image with Python 3.12
FROM supervisely/base-py3.12:0.0.1

# Updating system packages and upgrading pip through apt
RUN apt-get update && apt-get install -y --no-install-recommends \
    zlib1g-dev \
    libmagic-dev \
    && apt-get upgrade -y python3-pip \
    && apt-get -qq -y autoremove \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/*

# Installing updated dependencies (using latest compatible versions)
RUN pip install --no-cache-dir --break-system-packages \
    "attrs>=23.1.0" \
    "requests>=2.31.0" \
    "Werkzeug>=2.3.7" \
    "MarkupSafe>=2.1.3" \
    "beautifulsoup4>=4.12.2" \
    "ruamel.yaml>=0.17.32"

# Installing from specific GitHub branch (protobuf-dependencies-update)
# No build args needed since we're installing from specific branch

# Installing Supervisely SDK from specific GitHub branch
RUN pip install --upgrade --break-system-packages git+https://github.com/supervisely/supervisely.git@protobuf-dependencies-update
RUN pip install --upgrade --break-system-packages "git+https://github.com/supervisely/supervisely.git@protobuf-dependencies-update#egg=supervisely[apps]"
RUN pip install --upgrade --break-system-packages "git+https://github.com/supervisely/supervisely.git@protobuf-dependencies-update#egg=supervisely[aug]"

# Verifying installation
RUN python -c "import supervisely as sly; print(f'Supervisely SDK: {sly.__version__}')"

# Labels for identification
LABEL maintainer="Supervisely Team"
LABEL python.version="3.12"
LABEL ubuntu.version="24.04" 
LABEL supervisely.sdk.branch="protobuf-dependencies-update"
LABEL description="Supervisely SDK image with Python 3.12 on Ubuntu 24.04 (protobuf-dependencies-update branch)"
