version: '2.4'
services:
  sphinx-docs:
    image: ferrum848/alex_sphinxdoc
    runtime: runc
    build: .
    volumes:
    - ./build:/app/build
    - ./source:/app/source
    - ../help:/app/source/repo/help:ro
    - ../supervisely_lib:/app/source/repo/supervisely_lib:ro

  cleanbuild:
    image: ferrum848/alex_sphinxdoc
    runtime: runc
    command: find "/app/build" -mindepth 1 -delete
    volumes:
    - ./build:/app/build
    
