name: Manual run SDK NVIDIA pyindex Docker

on:
  workflow_dispatch

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Write Tag to ENV variable
      run: echo "RELEASE_VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: supervisely/sdk-nvidia-pyindex
        tags: ${{ env.RELEASE_VERSION }}, latest
        addLatest: true
        dockerfile: "base_images/sdk_nvidia_pyindex/Dockerfile"
        registry: docker.io
        buildArgs: |
          tag_ref_name=${{ env.RELEASE_VERSION }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
